Feature/signup
wecode-bootcamp-korea/40-1st-Meet-Meat-backend pull request #2
Opened 2022-12-07 12:41 UTC by JasonJeongjaeheon

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- signup 기능 구현

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- userController layer : client request 내 데이터 누락시 에러 반환
- userService layer : password, email 정규 표현식 활용하여 검증 및 에러 반환
- userService layer : bcrypt 활용하여 user password 암호화
- userDao layer : 암호화 password DB에 저장 및 email 중복 또는 잘못된 데이터 저장시 에러 반환

<br />

## :: 테스트 결과 이미지
1. POST 결과 캡처 이미지
2. 데이터 DB 저장 캡처 이미지
3. 에러 반환 캡처 이미지

<br />

## :: 기타 질문 및 특이 사항
- layered pattern 으로 코드를 구현하는 것에 대하여 추가 공부 필요
- 에러 핸들링에 대한 추가 공부 필요

2022-12-08 05:24 UTC, kyeongraekim requested changes
auth.js 에 대한 인가 코드와 로그인에 대한 내용도 추후에 함께 푸시해주세요!~

2022-12-08 05:24 UTC, kyeongraekim commented on api/models/userDao.js
> +}
해당 에러 핸들링을 try-catch 형태에서, layered pattern 관련 전달드린 인증/인가 모델 예시에서 볼 수 있었던 globalErrorHandler 개념을 적용하여 변경해 보는 것은 어떠실까요? 
전체 프로젝트에서 발생가능한 에러를 하나의 모듈이 제어한다는 이점이 있습니다.

2022-12-08 11:26 UTC, JasonJeongjaeheon commented
global error handling에 대하여 좀 더 이해가 필요한 것 같습니다. 일단 이해한 바로는 말 그대로 서버 전체에서 이뤄지는 데이터의 흐름 가운데 발생하는 에러를 반환하도록 만드는 것으로 이해하고 코드 작성해보았습니다. 더불어 catchasync의 경우에는 비동기 처리 가운데 err를 그 함수가 이뤄지는 블록에서 잡아 에러 반환을 하는 경우에 하는 것이 맞는지도 함께 의견 부탁 드리겠습니다. 감사합니다 :)

2022-12-09 04:44 UTC, kyeongraekim requested changes

2022-12-09 04:44 UTC, kyeongraekim commented on api/services/userService.js
> +    const hashedPassword = await bcrypt.hash(password, 10);
해당 saltRound가 10으로 하드코딩 되어있는데 변수에 선언해서 별도로 관리해주세요!~ 
웹서비스 개발에서의 하드코딩은 대부분 필히 지양해주셔야 합니다

2022-12-09 05:12 UTC, JasonJeongjaeheon commented
넵! 변수에 할당하여 관리하는 것으로 수정하였습니다. 다음 기능 구현에도 관련 내용 신경써서 작업하겠습니다. 감사합니다.

2022-12-09 07:54 UTC, kyeongraekim approved these changes
LGTM

2022-12-09 07:54 UTC, merged