포인트차감을위한 구매 항목별 총가격 데이터전달 API 및 유저의 로그인(접속)상태 확인  API
wecode-bootcamp-korea/40-1st-Meet-Meat-backend pull request #5
Opened 2022-12-13 11:59 UTC by hjcod

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- 포인트차감을위한 구매 항목별 총가격 데이터전달 API
- 유저의 로그인(접속)상태 확인  API

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- API 호출 시 필요한 값들에 대한 유효성 검사 

## :: 테스트 결과 이미지

![for point](https://user-images.githubusercontent.com/106718631/207311480-aaa2dd32-d7e9-4ac6-abd3-c13b09be641f.png)

## :: 기타 질문 및 특이 사항
- 항목별 총가격이아닌 유저의 기존 point 에서 총가격(point)차감을 진행해보는걸 생각해보면 좋을 것 같다.

2022-12-14 03:40 UTC, kyeongraekim requested changes

2022-12-14 03:40 UTC, kyeongraekim commented on api/models/pointDao.js
> +const getTotalpoint = async (id) =>{
변수명 camelCase가 다소 아쉽네요!~

2022-12-14 03:40 UTC, kyeongraekim commented on api/models/pointDao.js
> +       ON order_items.orders_id = orders.id where customers_id =?
가독성을 위해 Where 절을 line breaking 해주세요!~

2022-12-14 03:40 UTC, kyeongraekim commented on api/models/pointDao.js
> +            total_price_with_point
해당 total_price_with_point는 별도의 컬럼으로 존재하는 건가요? 오후에 설명 들으러 찾아뵐게요!~

2022-12-14 07:26 UTC, hjcod commented on api/models/pointDao.js
> +            total_price_with_point
별도의 컬럼명으로 존재합니다!

2022-12-14 12:59 UTC, kyeongraekim requested changes

2022-12-14 12:59 UTC, kyeongraekim commented on api/models/paymentDao.js
> +
불필요한 whitespace를 제거해주세요!~

2022-12-14 12:59 UTC, kyeongraekim commented on api/models/paymentDao.js
> +const { SimpleConsoleLogger } = require('typeorm');
해당 내용은 사용하지 않는 모듈처럼 보이는데, 사용하지 않는 내역은 삭제해주세요!~

2022-12-14 12:59 UTC, kyeongraekim commented on api/models/paymentDao.js
> +    return sumpoint;
해당 내역은 transaction이라고 하는, payment 중도 에러시 rollback 할 수 있는 내역이 추가 되어야 합니다. payment 결제에 대한 내역은 데이터의 원자성, 일관성, 독립성, 지속성을 위해 꼭 설정해야 함으로 typeORM의 트랜잭션 개념을 꼭 추가해주세요!~ 
관련 내용 [링크 공유해드립니다!](https://mommoo.tistory.com/62)

2022-12-15 15:06 UTC, kyeongraekim approved these changes

2022-12-15 15:06 UTC, merged